use async_trait::async_trait;

/// The application context received by Rust controllers
/// upon `handle` invocation. Provides async access to the DOM.
#[derive(Clone)]
pub struct AppContext {
    pub dom: crate::dom::RustDOM,
    pub store: crate::store::Store,
}

#[async_trait]
pub trait AlakitController: Send + Sync {
    async fn handle(&self, cmd: &str, args: &str, ctx: AppContext);
    
    #[allow(unused_variables)]
    async fn handle_binary(&self, cmd: &str, payload: &[u8], ctx: AppContext) {
        // Overridable method for receiving binary data.
    }
}

// Controller registration data generated by the macro.
pub struct ControllerRegistration {
    pub namespace: &'static str,
    // Controller instantiating function (factory).
    pub factory: fn() -> Box<dyn AlakitController + Send + Sync>,
}

inventory::collect!(ControllerRegistration);
